# Generated by Django 4.0.5 on 2022-08-18 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_verifications_verification_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='location',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='social_youtube',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='username',
            new_name='timezone',
        ),
    ]
