# Generated by Django 4.0.5 on 2022-08-18 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_location_developer_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='short_intro',
            new_name='hero',
        ),
    ]
