# Generated by Django 4.0.5 on 2022-08-18 04:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_short_intro_developer_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('part_time_contract', models.BooleanField(default=False, null=True)),
                ('full_time_contract', models.BooleanField(default=False, null=True)),
                ('full_time_job', models.BooleanField(default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('developer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.developer')),
            ],
        ),
        migrations.CreateModel(
            name='RoleLevel',
            fields=[
                ('junior', models.BooleanField(default=False, null=True)),
                ('mid', models.BooleanField(default=False, null=True)),
                ('senior', models.BooleanField(default=False, null=True)),
                ('principal', models.BooleanField(default=False, null=True)),
                ('c_level', models.BooleanField(default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('developer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.developer')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('available', models.BooleanField(default=False, null=True)),
                ('open', models.BooleanField(default=False, null=True)),
                ('not_available', models.BooleanField(default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('developer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.developer')),
            ],
        ),
    ]
