# Generated by Django 4.0.5 on 2022-08-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_roletype_rolelevel_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='email',
        ),
        migrations.AlterField(
            model_name='developer',
            name='timezone',
            field=models.CharField(choices=[('-12:00', '(GMT -12:00)'), ('-11:00', '(GMT -11:00)'), ('-10:00', '(GMT -10:00)'), ('-09:00', '(GMT -09:00)'), ('-08:00', '(GMT -08:00)'), ('-07:00', '(GMT -07:00)'), ('-06:00', '(GMT -06:00)'), ('-05:00', '(GMT -05:00)'), ('-04:00', '(GMT -04:00)'), ('-03:00', '(GMT -03:00)'), ('-02:00', '(GMT -02:00)'), ('-01:00', '(GMT -01:00)'), ('+00:00', '(GMT)'), ('+01:00', '(GMT +01:00)'), ('+02:00', '(GMT +02:00)'), ('+03:00', '(GMT +03:00)'), ('+04:00', '(GMT +04:00)'), ('+05:00', '(GMT +05:00)'), ('+06:00', '(GMT +06:00)'), ('+07:00', '(GMT +07:00)'), ('+08:00', '(GMT +08:00)'), ('+09:00', '(GMT +09:00)'), ('+10:00', '(GMT +10:00)'), ('+11:00', '(GMT +11:00)'), ('+12:00', '(GMT +12:00)')], default='+00:00', max_length=6),
        ),
    ]
