# Generated by Django 4.0.5 on 2022-08-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_developer_bio_alter_developer_hero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
