# Generated by Django 4.0.5 on 2022-08-29 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_name_message_receipter_remove_message_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='body',
        ),
    ]
