# Generated by Django 4.0.5 on 2022-08-29 04:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_conversation_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
