# Generated by Django 4.0.5 on 2022-08-29 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_message_sender_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_id',
        ),
        migrations.AddField(
            model_name='message',
            name='sender_id_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.business'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_id_developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.developer'),
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
