# Generated by Django 4.0.5 on 2022-08-29 18:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_message_conversation_remove_message_sender_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBusinessToDeveloper',
            fields=[
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('receipter_id_developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.developer')),
                ('sender_id_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.business')),
            ],
            options={
                'ordering': ['is_read', '-created'],
            },
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
