# Generated by Django 4.0.5 on 2022-08-30 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_messagebusinesstodeveloper_receipter_id_developer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagebusinesstodeveloper',
            name='receipter_id_developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.developer'),
        ),
        migrations.AlterField(
            model_name='messagebusinesstodeveloper',
            name='sender_id_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.business'),
        ),
    ]
