# Generated by Django 4.0.5 on 2022-08-31 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_conversation_business_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='business_id',
        ),
        migrations.AddField(
            model_name='conversation',
            name='business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.business'),
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='developer_id',
        ),
        migrations.AddField(
            model_name='conversation',
            name='developer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.developer'),
        ),
    ]
