# Generated by Django 4.0.5 on 2022-09-05 18:22

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_message_conversation_message_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='profile_image',
            field=models.ImageField(blank=True, default='business-profiles/user-default.png', null=True, upload_to='business/', validators=[users.models.file_size]),
        ),
        migrations.AlterField(
            model_name='developer',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/', validators=[users.models.file_size]),
        ),
    ]
