# Generated by Django 4.0.5 on 2022-09-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_developer_pay_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='hero',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
