# Generated by Django 4.0.5 on 2022-10-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_developer_city_alter_developer_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='social_github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='social_linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='social_twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='social_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
