# Generated by Django 4.0.5 on 2022-10-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_developer_social_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='pay_rate',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
